# this is demo project

spring:
  application:
    name: service-hi
# mvc:
#   view:
#     prefix: /WEB-INF/jsp/
#     suffix: .jsp
    
server:
  port: 8765
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#   instance:
#     preferIpAddress: true